### ISSUE TITLE
Language specification not clear

### ISSUE THREAD

**Issue by leonardoInf** [ykmnkmi/renderable#1]
Hi, it is possible that me or others want to help create this new templating language/parser + scanner but it is not clear to me what you are aiming for, i.e. what exactly is the syntax and which features you are trying to implement which are not present in Jinja / Stencil.

Have a nice day,

Leonardo

**Comment by ykmnkmi** [comment]
Hi, since in the jinja package parsing goes directly to the node tree, there will be difficulties with writing the generator and extension, also fix issue with php syntax. In this package I plan to write a tokenizer and a parser, with basic expressions and blocks, and a generator.
which after I transfer to jinja package.
My English is not so good.
